# Generated by Django 4.0.4 on 2022-07-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='seller',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
